########################################
# create images which includes:
# 	centos7 + systemd + postgresql9.4 + pacemaker + corosync
#
#############

FROM centos:7
MAINTAINER Gary

## enable systemd
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
    rm -f /lib/systemd/system/multi-user.target.wants/*;\
    rm -f /etc/systemd/system/*.wants/*;\
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*;\
    rm -f /lib/systemd/system/anaconda.target.wants/*;

RUN yum install -y http://yum.postgresql.org/9.4/redhat/rhel-6-x86_64/pgdg-redhat94-9.4-1.noarch.rpm

RUN yum update -y

RUN yum -y install postgresql94-server postgresql94-contrib pacemaker pcs psmisc policycoreutils-python

RUN alias cp='cp'

RUN cp -rf /usr/pgsql-9.4/bin/* /usr/bin/;\
    cp -rf /usr/pgsql-9.4/lib/* /usr/lib/;\
    cp -rf /usr/pgsql-9.4/share/* /usr/share/;\
    rm -rf /usr/pgsql-9.4/bin/;\
    rm -rf /usr/pgsql-9.4/lib/;\
    rm -rf /usr/pgsql-9.4/share/;

VOLUME [ "/sys/fs/cgroup" ]

CMD ["/usr/sbin/init"]
